# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/lovely-docs',
                'doc_host': 'https://xl0.github.io',
                'git_url': 'https://github.com/xl0/lovely-docs',
                'lib_path': 'lovely_docs'},
  'syms': {'lovely_docs.sveltejs-svelte': {}, 'lovely_docs.utils': {}}}
