# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/13_neverthrow.ipynb.

# %% auto 0
__all__ = ['logger', 'source', 'commit', 'clone_dir', 'tree', 'processed_tree']

# %% ../nbs/13_neverthrow.ipynb 3
from .settings import settings, GitSource
from .git import clone_repo
from lovely_docs.docs import (
    build_markdown_doc_tree,
    process_tree_depth_first,
    calculate_total_usage,
    calculate_cost,
    save_processed_documents
)
import logging

# %% ../nbs/13_neverthrow.ipynb 4
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

# %% ../nbs/13_neverthrow.ipynb 6
source =  GitSource(
    name="neverthrow",
    doc_dir=".",
    include=["README.md"],
    repo="https://github.com/supermacro/neverthrow",
    commit="master",
    ecosystems=["webdev", "js"])


commit, clone_dir = clone_repo(source)
source.commit = commit # Replace the literal commit (master) with the hash

# %% ../nbs/13_neverthrow.ipynb 8
tree = build_markdown_doc_tree(clone_dir/source.doc_dir, include=["README.md"])

# %% ../nbs/13_neverthrow.ipynb 13
processed_tree = await process_tree_depth_first(settings, tree, source.name)

# %% ../nbs/13_neverthrow.ipynb 18
save_processed_documents(source, settings.output_dir / source.name.replace("/", "_"), processed_tree)
