# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/14_vercel-ai.ipynb.

# %% auto 0
__all__ = ['logger', 'source', 'commit', 'clone_dir', 'tree', 'processed_tree']

# %% ../nbs/14_vercel-ai.ipynb 3
from .settings import settings, GitSource
from .git import clone_repo
from lovely_docs.docs import (
    build_markdown_doc_tree,
    process_tree_depth_first,
    calculate_total_usage,
    calculate_cost,
    save_processed_documents
)
import logging

# %% ../nbs/14_vercel-ai.ipynb 4
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

# %% ../nbs/14_vercel-ai.ipynb 6
source =  GitSource(
    name="vercel/ai",
    doc_dir="content/docs",
    repo="https://github.com/vercel/ai",
    commit="main",
    ecosystems=["js"])


commit, clone_dir = clone_repo(source)
source.commit = commit # Replace the literal commit (master) with the hash

# %% ../nbs/14_vercel-ai.ipynb 8
tree = build_markdown_doc_tree(clone_dir/source.doc_dir, extensions=['.mdx'], exclude=["08-migration-guides"])
tree

# %% ../nbs/14_vercel-ai.ipynb 11
processed_tree = await process_tree_depth_first(settings, tree, source.name)

# %% ../nbs/14_vercel-ai.ipynb 15
save_processed_documents(source, settings.output_dir / source.name.replace("/", "_"), processed_tree)
